/**
 * Overlay catalog gate for Just Go consumer voice (server).
 * Keep in sync with Meridian-Mobile/src/pivot/copy/pivotCopyCatalog.ts
 * and pivotCopyTokens.ts (`PIVOT_COPY_TOKEN_DEFAULTS` keys).
 *
 * Shipped defaults live in `pivotCopyDefaults.json`, generated by
 * `Meridian-Mobile/scripts/generate-pivot-copy-defaults.cjs`.
 * ICU is not parsed on write — the client falls back on a broken template.
 */

const PIVOT_COPY_DEFAULTS = require('./pivotCopyDefaults.json');

const PIVOT_COPY_SCHEMA_VERSION = 1;

const PIVOT_COPY_REMOTE_SECTIONS = Object.freeze([
  'brand',
  'placeholders',
  'ticker',
  'welcome',
  'entry',
  'referral',
  'auth',
  'onboarding',
  'interestsOnboarding',
  'calendarOnboarding',
  'themeOnboarding',
  'ageOnboarding',
  'week',
  'explore',
  'recap',
  'plans',
  'friends',
  'invite',
  'inviteDeepLink',
  'eventDetail',
  'cardStack',
  'swipeTutorial',
  'calendar',
  'feedback',
  'profile',
  'social',
  'editInterests',
  'accountSettings',
  'crew',
  // Phase 6.2 — web landing
  'landing',
]);

const PIVOT_COPY_DENIED_SECTIONS = Object.freeze([
  'admin',
  'demo',
  'dev',
  'network',
  'mobile',
]);

const PIVOT_COPY_NON_COPY_LEAVES = Object.freeze(['interestBleedSubtitleEnabled']);

const PIVOT_COPY_TOKEN_NAMES = Object.freeze([
  'brand.name',
  'brand.cta',
  'group.singular',
  'group.plural',
]);

const COPY_ENTRY_MAX_LENGTH = 500;
const COPY_TOKEN_MAX_LENGTH = 240;
/** Editor saves one key or a small batch — never the full catalog. */
const COPY_PATCH_MAX_KEYS = 20;

const CATALOG_SCHEMA_VERSION =
  Number(PIVOT_COPY_DEFAULTS.schemaVersion) || PIVOT_COPY_SCHEMA_VERSION;

const CATALOG_SHIPPED_TOKENS = Object.freeze({
  ...(PIVOT_COPY_DEFAULTS.tokens || {}),
});

const CATALOG_KEYS = Object.freeze(
  Array.isArray(PIVOT_COPY_DEFAULTS.keys) ? PIVOT_COPY_DEFAULTS.keys : [],
);

const CATALOG_SHIPPED_ENTRIES = Object.freeze(
  Object.fromEntries(
    CATALOG_KEYS.filter((key) => key && typeof key.path === 'string').map(
      (key) => [key.path, key.shipped],
    ),
  ),
);

const CATALOG_ENTRY_SET = new Set(Object.keys(CATALOG_SHIPPED_ENTRIES));

const REMOTE_SECTION_SET = new Set(PIVOT_COPY_REMOTE_SECTIONS);
const DENIED_SECTION_SET = new Set(PIVOT_COPY_DENIED_SECTIONS);
const NON_COPY_LEAF_SET = new Set(PIVOT_COPY_NON_COPY_LEAVES);
const TOKEN_NAME_SET = new Set(PIVOT_COPY_TOKEN_NAMES);

/** `week.adminNextDeckCta`, `profile.devResetWeekTitle`, … */
const DENIED_LEAF_PREFIX = /^(admin|dev)[A-Z]/;
/** `mobile.updateGateTitle` and any future `*.updateGate*` leaf. */
const UPDATE_GATE_PREFIX = /^updateGate/;

function isDeniedCopySegment(segment) {
  return (
    segment === 'admin' ||
    segment === 'demo' ||
    segment === 'dev' ||
    DENIED_LEAF_PREFIX.test(segment) ||
    UPDATE_GATE_PREFIX.test(segment)
  );
}

/**
 * Whether a dotted `PIVOT_COPY` path may appear in a remote pack.
 * Section-only paths, unknown sections, denied sections, nested admin/dev
 * ops keys, update-gate strings, and leaked config leaves return false.
 */
function isRemoteCopyKey(path) {
  if (!path || typeof path !== 'string') {
    return false;
  }
  const segments = path.split('.');
  if (segments.length < 2 || segments.some((segment) => segment.length === 0)) {
    return false;
  }
  const [section, ...rest] = segments;
  if (DENIED_SECTION_SET.has(section) || !REMOTE_SECTION_SET.has(section)) {
    return false;
  }
  const leaf = rest[rest.length - 1];
  if (NON_COPY_LEAF_SET.has(leaf) || rest.some(isDeniedCopySegment)) {
    return false;
  }
  return true;
}

function isCopyTokenName(name) {
  return typeof name === 'string' && TOKEN_NAME_SET.has(name);
}

function isCatalogCopyKey(path) {
  return typeof path === 'string' && CATALOG_ENTRY_SET.has(path);
}

function getShippedCopyEntry(path) {
  return isCatalogCopyKey(path) ? CATALOG_SHIPPED_ENTRIES[path] : undefined;
}

function getShippedCopyToken(name) {
  return isCopyTokenName(name) ? CATALOG_SHIPPED_TOKENS[name] : undefined;
}

module.exports = {
  PIVOT_COPY_SCHEMA_VERSION,
  PIVOT_COPY_REMOTE_SECTIONS,
  PIVOT_COPY_DENIED_SECTIONS,
  PIVOT_COPY_NON_COPY_LEAVES,
  PIVOT_COPY_TOKEN_NAMES,
  COPY_ENTRY_MAX_LENGTH,
  COPY_TOKEN_MAX_LENGTH,
  COPY_PATCH_MAX_KEYS,
  CATALOG_SCHEMA_VERSION,
  CATALOG_KEYS,
  CATALOG_SHIPPED_ENTRIES,
  CATALOG_SHIPPED_TOKENS,
  isRemoteCopyKey,
  isCopyTokenName,
  isCatalogCopyKey,
  getShippedCopyEntry,
  getShippedCopyToken,
};
